"use client"

import { useState } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Sparkles, Download, Loader2, AlertCircle, FileText } from "lucide-react"
import { generateStrategyBriefAction, type StrategyBriefResponse } from "@/lib/api-actions"

interface StrategyBriefProps {
  countryCode: string
  countryName: string
  countryFlag: string
  debtAmount: number
  reliefPercent: number
}

export function StrategyBrief({
  countryCode,
  countryName,
  countryFlag,
  debtAmount,
  reliefPercent,
}: StrategyBriefProps) {
  const [brief, setBrief] = useState<StrategyBriefResponse | null>(null)
  const [isGenerating, setIsGenerating] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const handleGenerate = async () => {
    setIsGenerating(true)
    setError(null)

    try {
      const result = await generateStrategyBriefAction({
        country_code: countryCode,
        debt_amount_usd: debtAmount,
        relief_percent: reliefPercent,
      })
      setBrief(result)
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to generate strategy brief")
    } finally {
      setIsGenerating(false)
    }
  }

  const handleDownloadPDF = () => {
    if (!brief) return

    // Build a clean HTML document for printing as PDF
    const printContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Strategy Brief - ${brief.country.name}</title>
  <style>
    @page { margin: 1in; size: A4; }
    body {
      font-family: 'Georgia', 'Times New Roman', serif;
      color: #1a1a1a;
      line-height: 1.6;
      max-width: 100%;
      margin: 0;
      padding: 0;
    }
    .header {
      border-bottom: 3px solid #1e3a5f;
      padding-bottom: 16px;
      margin-bottom: 24px;
    }
    .header h1 {
      font-size: 22px;
      color: #1e3a5f;
      margin: 0 0 4px 0;
    }
    .header .subtitle {
      font-size: 13px;
      color: #666;
    }
    .header .params {
      font-size: 12px;
      color: #444;
      margin-top: 8px;
    }
    .badge {
      display: inline-block;
      background: #1e3a5f;
      color: white;
      padding: 2px 10px;
      border-radius: 4px;
      font-size: 11px;
      font-family: sans-serif;
      letter-spacing: 0.5px;
      text-transform: uppercase;
      margin-bottom: 12px;
    }
    h2 {
      font-size: 15px;
      color: #1e3a5f;
      border-bottom: 1px solid #ddd;
      padding-bottom: 4px;
      margin-top: 20px;
      margin-bottom: 10px;
    }
    p { font-size: 13px; margin: 8px 0; }
    ul, ol { font-size: 13px; margin: 8px 0; padding-left: 24px; }
    li { margin-bottom: 4px; }
    strong { color: #1e3a5f; }
    .footer {
      margin-top: 32px;
      padding-top: 12px;
      border-top: 1px solid #ddd;
      font-size: 10px;
      color: #999;
      font-family: sans-serif;
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="badge">Confidential — Strategy Brief</div>
    <h1>Negotiation Strategy: ${brief.country.name}</h1>
    <div class="subtitle">${brief.country.region} · ${brief.country.income_level}</div>
    <div class="params">
      Debt Under Review: $${(brief.parameters.debt_amount_usd / 1_000_000).toFixed(1)}M USD
      · Target Relief: ${brief.parameters.relief_percent}%
      · Potential Savings: $${(brief.parameters.potential_savings_usd / 1_000_000).toFixed(1)}M USD
    </div>
  </div>
  ${formatBriefToHTML(brief.brief)}
  <div class="footer">
    Generated by The Borrower's Forum — AI Strategy Advisor · ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
    · Based on ${brief.precedents_used} comparable precedents and ${brief.climate_precedents_used} climate-linked cases
  </div>
</body>
</html>`

    const printWindow = window.open("", "_blank")
    if (printWindow) {
      printWindow.document.write(printContent)
      printWindow.document.close()
      // Wait for content to render, then trigger print
      setTimeout(() => {
        printWindow.print()
      }, 500)
    }
  }

  // Not yet generated — show the trigger button
  if (!brief && !isGenerating && !error) {
    return (
      <Card className="border-2 border-dashed border-[#1e3a5f]/20 bg-gradient-to-br from-[#1e3a5f]/5 to-transparent">
        <CardContent className="py-8">
          <div className="text-center space-y-4">
            <div className="inline-flex p-4 rounded-full bg-[#1e3a5f]/10">
              <Sparkles className="h-8 w-8 text-[#1e3a5f]" />
            </div>
            <div>
              <h3 className="text-xl font-bold text-[#1e3a5f]">AI Strategy Advisor</h3>
              <p className="text-sm text-slate-600 max-w-md mx-auto mt-2">
                Generate a confidential negotiation strategy brief for {countryName}, informed by
                comparable precedents and climate-linked restructuring cases.
              </p>
            </div>
            <Button
              onClick={handleGenerate}
              size="lg"
              className="gradient-navy hover:opacity-90 text-white shadow-lg shadow-[#1e3a5f]/20"
            >
              <Sparkles className="mr-2 h-5 w-5" />
              Get AI Strategy Brief
            </Button>
          </div>
        </CardContent>
      </Card>
    )
  }

  // Generating state
  if (isGenerating) {
    return (
      <Card className="border border-[#1e3a5f]/20 bg-gradient-to-br from-[#1e3a5f]/5 to-transparent">
        <CardContent className="py-12">
          <div className="text-center space-y-4">
            <div className="inline-flex p-4 rounded-full bg-[#1e3a5f]/10 animate-pulse">
              <Sparkles className="h-8 w-8 text-[#1e3a5f]" />
            </div>
            <div>
              <h3 className="text-lg font-semibold text-[#1e3a5f]">Generating Strategy Brief...</h3>
              <p className="text-sm text-slate-500 mt-2">
                Analyzing {countryName}&apos;s debt profile against comparable precedents
              </p>
            </div>
            <div className="flex items-center justify-center gap-2 text-sm text-slate-500">
              <Loader2 className="h-4 w-4 animate-spin" />
              <span>This takes 10-15 seconds</span>
            </div>
          </div>
        </CardContent>
      </Card>
    )
  }

  // Error state
  if (error) {
    return (
      <Card className="border border-red-200 bg-red-50/50">
        <CardContent className="py-8">
          <div className="text-center space-y-4">
            <AlertCircle className="h-8 w-8 text-red-500 mx-auto" />
            <div>
              <h3 className="text-lg font-semibold text-red-800">Could not generate brief</h3>
              <p className="text-sm text-red-600 mt-1">{error}</p>
            </div>
            <Button onClick={handleGenerate} variant="outline" className="border-red-200 text-red-700 bg-transparent">
              Try Again
            </Button>
          </div>
        </CardContent>
      </Card>
    )
  }

  // Brief generated — display it
  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-lg gradient-navy">
            <Sparkles className="h-5 w-5 text-white" />
          </div>
          <div>
            <h2 className="text-xl font-bold text-slate-900">AI Strategy Brief</h2>
            <p className="text-xs text-slate-500">
              Based on {brief!.precedents_used} comparable precedents &middot; {brief!.climate_precedents_used} climate-linked cases
            </p>
          </div>
        </div>
        <div className="flex gap-2">
          <Button onClick={handleDownloadPDF} variant="outline" size="sm" className="bg-transparent">
            <Download className="mr-2 h-4 w-4" />
            Download as PDF
          </Button>
          <Button onClick={handleGenerate} variant="outline" size="sm" className="bg-transparent">
            <Sparkles className="mr-2 h-4 w-4" />
            Regenerate
          </Button>
        </div>
      </div>

      <Card className="border border-[#1e3a5f]/15 shadow-lg">
        {/* Brief header bar */}
        <div className="gradient-navy px-6 py-4 rounded-t-lg">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <FileText className="h-5 w-5 text-white/80" />
              <div>
                <p className="text-white font-semibold">
                  {countryFlag} Negotiation Strategy: {brief!.country.name}
                </p>
                <p className="text-white/60 text-xs">
                  {brief!.country.region} &middot; {brief!.country.income_level}
                </p>
              </div>
            </div>
            <div className="text-right">
              <p className="text-white/80 text-sm font-mono">
                ${(brief!.parameters.debt_amount_usd / 1_000_000).toFixed(1)}M
              </p>
              <p className="text-white/50 text-xs">
                {brief!.parameters.relief_percent}% relief target
              </p>
            </div>
          </div>
        </div>

        {/* Brief content */}
        <CardContent className="py-8 px-6 md:px-10">
          <div
            className="prose prose-slate prose-sm max-w-none
              prose-headings:text-[#1e3a5f] prose-headings:border-b prose-headings:border-slate-200 prose-headings:pb-2 prose-headings:mb-3
              prose-h2:text-base prose-h2:font-bold prose-h2:mt-6
              prose-p:text-slate-700 prose-p:leading-relaxed
              prose-li:text-slate-700
              prose-strong:text-[#1e3a5f]
              prose-ul:my-2 prose-ol:my-2"
            dangerouslySetInnerHTML={{ __html: formatBriefToHTML(brief!.brief) }}
          />
        </CardContent>

        {/* Brief footer */}
        <div className="border-t border-slate-200 px-6 py-3 bg-slate-50 rounded-b-lg">
          <p className="text-xs text-slate-400 text-center">
            Generated by The Borrower&apos;s Forum AI Strategy Advisor &middot;{" "}
            {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
            &middot; Based on verified data from IMF, World Bank, and Paris Club sources
          </p>
        </div>
      </Card>
    </div>
  )
}

/**
 * Convert markdown-style brief text to HTML for display.
 * Handles: ## headings, **bold**, bullet lists, numbered lists, paragraphs.
 */
function formatBriefToHTML(markdown: string): string {
  const lines = markdown.split("\n")
  let html = ""
  let inList = false
  let listType: "ul" | "ol" | null = null

  for (const line of lines) {
    const trimmed = line.trim()

    if (!trimmed) {
      if (inList) {
        html += listType === "ul" ? "</ul>" : "</ol>"
        inList = false
        listType = null
      }
      continue
    }

    // Headings
    if (trimmed.startsWith("## ")) {
      if (inList) {
        html += listType === "ul" ? "</ul>" : "</ol>"
        inList = false
        listType = null
      }
      html += `<h2>${formatInline(trimmed.slice(3))}</h2>`
      continue
    }

    // Bullet lists
    if (trimmed.startsWith("- ") || trimmed.startsWith("* ")) {
      if (!inList || listType !== "ul") {
        if (inList) html += listType === "ul" ? "</ul>" : "</ol>"
        html += "<ul>"
        inList = true
        listType = "ul"
      }
      html += `<li>${formatInline(trimmed.slice(2))}</li>`
      continue
    }

    // Numbered lists
    const numberedMatch = trimmed.match(/^\d+\.\s+(.*)/)
    if (numberedMatch) {
      if (!inList || listType !== "ol") {
        if (inList) html += listType === "ul" ? "</ul>" : "</ol>"
        html += "<ol>"
        inList = true
        listType = "ol"
      }
      html += `<li>${formatInline(numberedMatch[1])}</li>`
      continue
    }

    // Regular paragraph
    if (inList) {
      html += listType === "ul" ? "</ul>" : "</ol>"
      inList = false
      listType = null
    }
    html += `<p>${formatInline(trimmed)}</p>`
  }

  if (inList) {
    html += listType === "ul" ? "</ul>" : "</ol>"
  }

  return html
}

/** Format inline markdown: **bold** */
function formatInline(text: string): string {
  return text.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
}
