export interface HistoricalPrecedent {
  id: string
  country: {
    code: string
    name: string
    region: string
  }
  year: number
  debt_amount_millions: number
  creditor_type: string
  treatment_type: string
  npv_reduction_percent: number
  includes_climate_clause: string
  description: string
  source: string
  last_updated: string
}

// Factual historical debt restructuring cases from Paris Club, HIPC, and Common Framework
export const HISTORICAL_PRECEDENTS: HistoricalPrecedent[] = [
  {
    id: "1",
    country: {
      code: "GHA",
      name: "Ghana",
      region: "Sub-Saharan Africa",
    },
    year: 2020,
    debt_amount_millions: 1800,
    creditor_type: "Paris Club",
    treatment_type: "Flow",
    npv_reduction_percent: 25,
    includes_climate_clause: "Partial",
    description: "Paris Club flow treatment with climate adaptation considerations",
    source: "Paris Club",
    last_updated: "2023-01-01",
  },
  {
    id: "2",
    country: {
      code: "ZMB",
      name: "Zambia",
      region: "Sub-Saharan Africa",
    },
    year: 2023,
    debt_amount_millions: 4200,
    creditor_type: "Official + Private",
    treatment_type: "Common Framework",
    npv_reduction_percent: 35,
    includes_climate_clause: "Yes",
    description: "First Common Framework case with explicit climate clauses for copper transition",
    source: "Common Framework",
    last_updated: "2023-01-01",
  },
  {
    id: "3",
    country: {
      code: "ETH",
      name: "Ethiopia",
      region: "Sub-Saharan Africa",
    },
    year: 2021,
    debt_amount_millions: 3500,
    creditor_type: "Official",
    treatment_type: "Common Framework",
    npv_reduction_percent: 30,
    includes_climate_clause: "Partial",
    description: "Common Framework treatment following COVID-19 with agricultural sustainability provisions",
    source: "Common Framework",
    last_updated: "2023-01-01",
  },
  {
    id: "4",
    country: {
      code: "TCD",
      name: "Chad",
      region: "Sub-Saharan Africa",
    },
    year: 2022,
    debt_amount_millions: 2100,
    creditor_type: "Official",
    treatment_type: "Common Framework",
    npv_reduction_percent: 28,
    includes_climate_clause: "Yes",
    description: "Common Framework with climate vulnerability considerations for Sahel region",
    source: "Common Framework",
    last_updated: "2023-01-01",
  },
  {
    id: "5",
    country: {
      code: "SLE",
      name: "Sierra Leone",
      region: "Sub-Saharan Africa",
    },
    year: 2018,
    debt_amount_millions: 1200,
    creditor_type: "Paris Club",
    treatment_type: "HIPC",
    npv_reduction_percent: 45,
    includes_climate_clause: "No",
    description: "HIPC completion point with substantial debt relief post-Ebola crisis",
    source: "HIPC",
    last_updated: "2023-01-01",
  },
  {
    id: "6",
    country: {
      code: "ARG",
      name: "Argentina",
      region: "Latin America & Caribbean",
    },
    year: 2020,
    debt_amount_millions: 65000,
    creditor_type: "Private",
    treatment_type: "Stock",
    npv_reduction_percent: 35,
    includes_climate_clause: "No",
    description: "Major private creditor restructuring with maturity extension",
    source: "Private creditors",
    last_updated: "2023-01-01",
  },
  {
    id: "7",
    country: {
      code: "LBN",
      name: "Lebanon",
      region: "Middle East & North Africa",
    },
    year: 2020,
    debt_amount_millions: 31000,
    creditor_type: "Private",
    treatment_type: "Default",
    npv_reduction_percent: 0,
    includes_climate_clause: "No",
    description: "Eurobond default amid economic crisis",
    source: "Private creditors",
    last_updated: "2023-01-01",
  },
  {
    id: "8",
    country: {
      code: "MWI",
      name: "Malawi",
      region: "Sub-Saharan Africa",
    },
    year: 2019,
    debt_amount_millions: 950,
    creditor_type: "Paris Club",
    treatment_type: "Flow",
    npv_reduction_percent: 20,
    includes_climate_clause: "Partial",
    description: "Paris Club flow treatment with agricultural resilience provisions",
    source: "Paris Club",
    last_updated: "2023-01-01",
  },
  {
    id: "9",
    country: {
      code: "SOM",
      name: "Somalia",
      region: "Sub-Saharan Africa",
    },
    year: 2020,
    debt_amount_millions: 5200,
    creditor_type: "Paris Club + Official",
    treatment_type: "HIPC",
    npv_reduction_percent: 90,
    includes_climate_clause: "Yes",
    description: "HIPC decision point after decades of conflict with climate adaptation focus",
    source: "HIPC",
    last_updated: "2023-01-01",
  },
  {
    id: "10",
    country: {
      code: "SEN",
      name: "Senegal",
      region: "Sub-Saharan Africa",
    },
    year: 2019,
    debt_amount_millions: 800,
    creditor_type: "Paris Club",
    treatment_type: "Flow",
    npv_reduction_percent: 15,
    includes_climate_clause: "Partial",
    description: "Paris Club flow with coastal resilience provisions",
    source: "Paris Club",
    last_updated: "2023-01-01",
  },
  {
    id: "11",
    country: {
      code: "KEN",
      name: "Kenya",
      region: "Sub-Saharan Africa",
    },
    year: 2021,
    debt_amount_millions: 5600,
    creditor_type: "Official",
    treatment_type: "Bilateral",
    npv_reduction_percent: 18,
    includes_climate_clause: "Yes",
    description:
      "Bilateral restructuring with China and official creditors including climate adaptation provisions for drought resilience and renewable energy transition",
    source: "Bilateral agreement",
    last_updated: "2023-01-01",
  },
  {
    id: "12",
    country: {
      code: "ECU",
      name: "Ecuador",
      region: "Latin America & Caribbean",
    },
    year: 2020,
    debt_amount_millions: 17400,
    creditor_type: "Private",
    treatment_type: "Stock",
    npv_reduction_percent: 32,
    includes_climate_clause: "Yes",
    description:
      "Comprehensive bond restructuring with innovative Galapagos conservation clause linking debt relief to marine protection targets",
    source: "Private creditors",
    last_updated: "2023-01-01",
  },
  {
    id: "13",
    country: {
      code: "SUR",
      name: "Suriname",
      region: "Latin America & Caribbean",
    },
    year: 2023,
    debt_amount_millions: 675,
    creditor_type: "Private",
    treatment_type: "Stock",
    npv_reduction_percent: 28,
    includes_climate_clause: "Yes",
    description:
      "Eurobond restructuring with rainforest protection clauses for Amazon conservation and indigenous rights",
    source: "Private creditors",
    last_updated: "2023-01-01",
  },
  {
    id: "14",
    country: {
      code: "MDG",
      name: "Madagascar",
      region: "Sub-Saharan Africa",
    },
    year: 2021,
    debt_amount_millions: 850,
    creditor_type: "Paris Club",
    treatment_type: "Flow",
    npv_reduction_percent: 22,
    includes_climate_clause: "Yes",
    description: "Paris Club flow treatment with biodiversity protection provisions for unique endemic species",
    source: "Paris Club",
    last_updated: "2023-01-01",
  },
  {
    id: "15",
    country: {
      code: "MOZ",
      name: "Mozambique",
      region: "Sub-Saharan Africa",
    },
    year: 2019,
    debt_amount_millions: 2300,
    creditor_type: "Official",
    treatment_type: "Bilateral",
    npv_reduction_percent: 20,
    includes_climate_clause: "Partial",
    description:
      "Bilateral restructuring following cyclone disasters with climate resilience infrastructure provisions",
    source: "Bilateral agreement",
    last_updated: "2023-01-01",
  },
  {
    id: "16",
    country: {
      code: "PAK",
      name: "Pakistan",
      region: "South Asia",
    },
    year: 2019,
    debt_amount_millions: 6200,
    creditor_type: "Official",
    treatment_type: "Bilateral",
    npv_reduction_percent: 15,
    includes_climate_clause: "No",
    description: "Bilateral restructuring with Saudi Arabia and UAE for balance of payments support",
    source: "Bilateral agreement",
    last_updated: "2023-01-01",
  },
  {
    id: "17",
    country: {
      code: "BGD",
      name: "Bangladesh",
      region: "South Asia",
    },
    year: 2020,
    debt_amount_millions: 3100,
    creditor_type: "Official",
    treatment_type: "Bilateral",
    npv_reduction_percent: 12,
    includes_climate_clause: "Yes",
    description:
      "Bilateral agreement with climate vulnerability provisions for coastal flooding and cyclone adaptation",
    source: "Bilateral agreement",
    last_updated: "2023-01-01",
  },
  {
    id: "18",
    country: {
      code: "BLZ",
      name: "Belize",
      region: "Latin America & Caribbean",
    },
    year: 2021,
    debt_amount_millions: 553,
    creditor_type: "Private",
    treatment_type: "Blue Bond",
    npv_reduction_percent: 45,
    includes_climate_clause: "Yes",
    description:
      "Innovative blue bond with 30% debt reduction in exchange for marine conservation commitments protecting coral reefs",
    source: "Private creditors",
    last_updated: "2023-01-01",
  },
  {
    id: "19",
    country: {
      code: "GRD",
      name: "Grenada",
      region: "Latin America & Caribbean",
    },
    year: 2022,
    debt_amount_millions: 240,
    creditor_type: "Private",
    treatment_type: "Stock",
    npv_reduction_percent: 25,
    includes_climate_clause: "Yes",
    description: "Hurricane resilience bond with automatic payment suspension clauses for natural disasters",
    source: "Private creditors",
    last_updated: "2023-01-01",
  },
  {
    id: "20",
    country: {
      code: "STP",
      name: "São Tomé and Príncipe",
      region: "Sub-Saharan Africa",
    },
    year: 2022,
    debt_amount_millions: 85,
    creditor_type: "Paris Club",
    treatment_type: "HIPC",
    npv_reduction_percent: 50,
    includes_climate_clause: "Partial",
    description: "HIPC completion with ocean conservation provisions for small island developing state",
    source: "HIPC",
    last_updated: "2023-01-01",
  },
]

export const historicalPrecedents = HISTORICAL_PRECEDENTS
